web/router.ex
defmodule Septima.Router do
  use Septima.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Septima do
    pipe_through [:browser, :browser_auth] # Use the default browser stack

    get "/", PageController, :index
    get "/logout", PageController, :logout
    get "/users", UserController, :index
  end

  scope "/auth", Septima do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Septima do
  #   pipe_through :api
  # end
end

lib/septima/endpoint.ex
defmodule Septima.Endpoint do
  use Phoenix.Endpoint, otp_app: :septima

  socket "/socket", Septima.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :septima, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_septima_key",
    signing_salt: "zVDtKVXm"

  plug Septima.Router
end

lib/septima/repo.ex
defmodule Septima.Repo do
  use Ecto.Repo, otp_app: :septima
end

web/models/authorization.ex
defmodule Septima.Authorization do
  use Septima.Web, :model

  schema "authorizations" do
    field :provider, :string
    field :uid, :string
    field :token, :string
    field :refresh_token, :string
    field :expired_at, :integer
    belongs_to :user, Septima.User
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:provider, :uid, :token, :refresh_token, :expired_at])
    |> validate_required([:provider, :uid, :token])
  end
end

web/models/user.ex
defmodule Septima.User do
  use Septima.Web, :model

  schema "users" do
    field :nombre, :string
    field :email, :string
    field :is_admin, :boolean, default: false

    has_many :authorizations, Septima.Authorization

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:nombre, :email, :is_admin])
    |> validate_required([:nombre, :email, :is_admin])
  end
end

web/controllers/auth_controller.ex
defmodule Septima.AuthController do
  use Septima.Web, :controller
  plug Ueberauth
  alias Septima.User
  alias Septima.UserFromAuth

  def request(conn, _params) do
    text conn, "Holi, no debo aparecer"
  end

  def callback(%{assigns: %{ueberauth_failure: _fails}} = conn, _params) do
    conn
    |> put_flash(:error, "Fallo en la authenticacion.")
    |> redirect(to: "/")
  end

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    case UserFromAuth.get_or_insert(auth, Repo) do
      {:ok, user} ->
        conn
        |> Guardian.Plug.sign_in(user, :token, perms: %{ default: [:read, :write]})
        |> redirect(to: page_path(conn, :index))
      {:error, _} ->
        conn
        |> put_flash(:error, "Fallo en la authenticacion.")
        |> redirect(to: "/")
    end
  end
end

web/controllers/page_controller.ex
defmodule Septima.PageController do
  use Septima.Web, :controller
  use Guardian.Phoenix.Controller

  def index(conn, _params, userlog, _claims) do
    render conn, "index.html", userlog: userlog
  end

  def logout(conn, _params, _userlog, _claims) do
    conn
    |> Guardian.Plug.sign_out
    |> put_flash(:info, "Logged out")
    |> redirect(to: "/")
  end
end

web/controllers/user_controller.ex
defmodule Septima.UserController do
  use Septima.Web, :controller
  use Guardian.Phoenix.Controller

  plug Guardian.Plug.EnsureAuthenticated, handler: __MODULE__
  plug Guardian.Plug.EnsurePermissions, handler: __MODULE__, admin: [:dashboard, :make_payments]

  def index(conn, _params, userlog, _claims) do
    render conn, "index.html", userlog: userlog
  end

  def unauthenticated(conn, _params) do
    conn
    |> put_flash(:error, "Logueate pues.")
    |> redirect(to: "/")
  end

  def unauthorized(conn, _params) do
    conn
    |> put_flash(:error, "No tienes permiso para users, solo admins")
    |> redirect(to: page_path(conn, :index))
  end
end

web/views/error_view.ex
defmodule Septima.ErrorView do
  use Septima.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Septima.LayoutView do
  use Septima.Web, :view
end

web/views/page_view.ex
defmodule Septima.PageView do
  use Septima.Web, :view
end

web/views/user_view.ex
defmodule Septima.UserView do
  use Septima.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Septima!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if @userlog do %>
            <%= link "logout", to: page_path(@conn, :logout), class: "btn" %>
            <%= else %>
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Login por Ueberauth</h2>
  <p class="lead"><%= link "Login with Github", to: auth_path(@conn, :request, "github"), class: "btn btn-success text-center" %></p>
</div>

web/templates/user/index.html.eex
<p>
  Holi, soy una pagina que necesita authenticacion
</p>